In [1]:
import torch

### TENSOR CREATIONS

In [2]:
# Creating a tensor from a list
tensor_1 = torch.tensor([1, 2, 3])
print("Tensor 1:", tensor_1)

# Creating a tensor filled with zeros
tensor_zeros = torch.zeros((2, 3))  # 2x3 matrix of zeros
print("Tensor of zeros:\n", tensor_zeros)

# Creating a tensor with random values
tensor_random = torch.randn((2, 3))  # 2x3 matrix with random values
print("Random tensor:\n", tensor_random)

# Checking the shape of a tensor
print("Shape of tensor_random:", tensor_random.shape)


Tensor 1: tensor([1, 2, 3])
Tensor of zeros:
 tensor([[0., 0., 0.],
        [0., 0., 0.]])
Random tensor:
 tensor([[ 0.8581, -0.8295,  1.3352],
        [ 0.0607, -1.5569, -1.1162]])
Shape of tensor_random: torch.Size([2, 3])


### TENSOR OPERATIONS

In [3]:
# Adding two tensors
tensor_2 = torch.tensor([4, 5, 6])
sum_tensor = tensor_1 + tensor_2
print("Sum of tensors:", sum_tensor)

# Matrix multiplication
matrix_1 = torch.tensor([[1, 2], [3, 4]])
matrix_2 = torch.tensor([[5, 6], [7, 8]])
product = torch.mm(matrix_1, matrix_2)
print("Matrix multiplication result:\n", product)

# Element-wise operations
elementwise_product = tensor_1 * tensor_2
print("Element-wise product:", elementwise_product)


Sum of tensors: tensor([5, 7, 9])
Matrix multiplication result:
 tensor([[19, 22],
        [43, 50]])
Element-wise product: tensor([ 4, 10, 18])


### GPU Operations

In [4]:
# Check if GPU is available
if torch.cuda.is_available():
    tensor_gpu = tensor_1.to("cuda")
    print("Tensor on GPU:", tensor_gpu)
else:
    print("GPU not available.")

GPU not available.


## Autograd in PyTorch

In [5]:
# Creating a tensor with requires_grad=True to track operations
x = torch.tensor(2.0, requires_grad=True)
y = x ** 2  # y = x^2

# Backward pass to calculate gradient
y.backward()

# Gradient of y with respect to x
print("Gradient of y with respect to x:", x.grad)

Gradient of y with respect to x: tensor(4.)


Autograd is PyTorch's automatic differentiation engine, which is essential for training neural networks. It allows PyTorch to automatically compute the gradients (derivatives) of tensors with respect to some defined loss or objective function. These gradients tell us how much each parameter (such as weights and biases in a model) contributes to the loss, guiding how we should adjust them to minimize the loss.

### Gradients and Computational Graphs